# MySQL ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 039444453392.dkr.ecr.us-east-1.amazonaws.com/clo835ecr-mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passwors"
        - name: MYSQL_DATABASE
          value: "employees"
      imagePullSecrets:
      - name: ecr-secret