name: Build and Push WebApp and MySQL Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Debug ECR_WEBAPP_URI
      run: |
        echo "ECR_WEBAPP_URI=>>${{ secrets.ECR_WEBAPP_URI }}<<"

    - name: Build and push WebApp image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.ECR_WEBAPP_URI }}:latest

    - name: Build and push MySQL image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile_mysql
        push: true
        tags: ${{ secrets.ECR_MYSQL_URI }}:latest
